# backend-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-backend-secrets
type: Opaque
data:
  # clé encodé: echo -n "sk-..." | base64
  OPENAI_API_KEY: "c2stcHJvai1vRHJFVmF5NGROUTNBVThyMTVZNTFoOTkwVEhSVXBIN3dWWjBfRUZIeFljOU1oQUdSbEw0U1E0U044LWNsZHFxVzFDbHh1SkdkM1QzQmxia0ZKYkJNbEE1MjdiZ1F0S3h6Wk9BZ0NudGtQNDJ3WUZkS1I3eXQ0RWVnNkUzUXp1N1NXTkR2eUh5UGttM2dBQzRpWjIxZjZUZ3BTUUE=" 
  
  # DATABASE_URL : L'URL de connexion à la DB de Michel
  # Pour l'instant, nous utilisons l'URL standard PostgreSQL (à modifier plus tard)
  DATABASE_URL: "cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bwb3N0Z3Jlc3FsOmY1NDMvY2hhdGRi" # Exemple: postgresql://user:pass@postgresql:5432/chatdb