apiVersion: v1
kind: Service
metadata:
  name: chatbot-frontend-service
  labels:
    app: chatbot-frontend
spec:
  selector:
    app: chatbot-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80 # Internal cluster port
      targetPort: 3000 # Container port
      nodePort: 30030 # Access via http://localhost:30030
  type: NodePort
